version: '3.8'

services:
  web:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - '8000:80'
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    env_file:
      - .env
