version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=phonebook_dev
    ports:
      - '27017:27017'
    volumes:
      - ./db/data:/data/db
      - ./db/scripts:/docker-entrypoint-initdb.d
  # app:
  #   build:
  #     context: ./client
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - server
  #     - mongodb
  # nginx:
  #   image: nginx:1.20.1
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8001:80
  #   container_name: reverse-proxy
  #   depends_on:
  #     - app # wait for the frontend container to be started
  #     - server
