version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=phonebook_dev
    ports:
      - '27017:27017'
    volumes:
      # - ./db/data:/data/db
      - ./db/scripts:/docker-entrypoint-initdb.d
  app:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 8000:5173
    depends_on:
      - server
      - mongodb
