name: Frontend CI/CD pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependecies
        working-directory: ./client
        run: npm install
      - name: Check style
        working-directory: ./client
        run: npm run lint
      - name: Run build
        working-directory: ./client
        run: npm run build
      - name: Run unit tests
        working-directory: ./client
        run: npm run test
